[package]
name = "lua-reqwest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.9", features = ["luajit", "module"] }
reqwest = { version = "0.12.7", features = ["blocking", "native-tls-alpn"] }
